plugins {
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'dev.architectury.loom' version '1.10-SNAPSHOT' apply false
    id 'com.gradleup.shadow' version '8.3.+' apply false
}

allprojects {
    apply plugin: 'java'

    version = "${project.mod_version}+mc${project.minecraft_version}"
    group = project.maven_group

    base {
        archivesName = project.mod_id
    }

    java {
        sourceCompatibility = targetCompatibility = JavaVersion.VERSION_21
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
    }
}

subprojects {
    apply plugin: 'architectury-plugin'
    apply plugin: 'dev.architectury.loom'

    repositories {
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com/releases/" }
    }

    dependencies {
        // to change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:1.21+build.4") // "hopes" and "prayers"
        }
    }

    processResources {
        def properties = [
                version          : project.version,
                minecraft_version: project.minecraft_version,
                mod_id           : project.mod_id,
                mod_name         : project.mod_name,
                mod_description  : project.mod_description
        ]

        inputs.properties properties
        filteringCharset "UTF-8"

        filesMatching(["fabric.mod.json", "META-INF/*mods.toml"]) {
            expand properties
        }
    }

    jar {
        from("LICENSE") {
            rename { "${it}_${project.mod_id}" }
        }
    }

    loom.runs.configureEach {
        property 'mixin.debug.export', 'true'
        property 'mixin.debug.verbose', 'true'
        property 'terminal.jline', 'true'
    }
}