org.gradle.jvmargs=-Xmx1G
#Fabric properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
#Mod properties
mod_version=1.0.0
maven_group=ru.berdinskiybear.armorhud
mod_id=ukus_armor_hud
mod_name=uku's Armor Hud
mod_description=This mod adds a minimalistic vanilla-like widget that shows your armor items and a warning if durability is low enough. Forked by uku.
#Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.116.0+1.21.1
neoforge_version=21.1.173
cloth_config_version=15.0.140
mod_menu_version=11.0.3
